-- Gratitude Quotes Seed Data
-- 366 quotes (one per day of year) for the gratitude_quotes table
-- Run this in Supabase SQL Editor
-- Quotes can be edited directly in the database at any time

-- Clear existing quotes first (idempotent)
DELETE FROM gratitude_quotes;

INSERT INTO gratitude_quotes (day_of_year, quote, author) VALUES
-- January (Days 1-31)
(1, 'Gratitude is not only the greatest of virtues but the parent of all the others.', 'Cicero'),
(2, 'Gratitude turns what we have into enough.', 'Melody Beattie'),
(3, 'The root of joy is gratefulness.', 'David Steindl-Rast'),
(4, 'When you are grateful, fear disappears and abundance appears.', 'Tony Robbins'),
(5, 'Gratitude is the sign of noble souls.', 'Aesop'),
(6, 'Acknowledging the good that you already have in your life is the foundation for all abundance.', 'Eckhart Tolle'),
(7, 'Gratitude makes sense of your past, brings peace for today, and creates a vision for tomorrow.', 'Melody Beattie'),
(8, 'Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.', 'Marcel Proust'),
(9, 'As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.', 'John F. Kennedy'),
(10, 'Gratitude is the wine for the soul. Go on. Get drunk.', 'Rumi'),
(11, 'He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.', 'Epictetus'),
(12, 'The real gift of gratitude is that the more grateful you are, the more present you become.', 'Robert Holden'),
(13, 'Enjoy the little things, for one day you may look back and realize they were the big things.', 'Robert Brault'),
(14, 'In ordinary life, we hardly realize that we receive a great deal more than we give, and that it is only with gratitude that life becomes rich.', 'Dietrich Bonhoeffer'),
(15, 'Gratitude is a powerful catalyst for happiness. It is the spark that lights a fire of joy in your soul.', 'Amy Collette'),
(16, 'The struggle ends when the gratitude begins.', 'Neale Donald Walsch'),
(17, 'Gratitude is the fairest blossom which springs from the soul.', 'Henry Ward Beecher'),
(18, 'When I started counting my blessings, my whole life turned around.', 'Willie Nelson'),
(19, 'Feeling gratitude and not expressing it is like wrapping a present and not giving it.', 'William Arthur Ward'),
(20, 'Piglet noticed that even though he had a very small heart, it could hold a rather large amount of gratitude.', 'A.A. Milne'),
(21, 'There is always, always, always something to be thankful for.', 'Unknown'),
(22, 'The thankful heart opens our eyes to a multitude of blessings that continually surround us.', 'James E. Faust'),
(23, 'Gratitude and attitude are not challenges; they are choices.', 'Robert Braathe'),
(24, 'Be thankful for what you have; you will end up having more.', 'Oprah Winfrey'),
(25, 'No one who achieves success does so without the help of others. The wise and confident acknowledge this help with gratitude.', 'Alfred North Whitehead'),
(26, 'We can only be said to be alive in those moments when our hearts are conscious of our treasures.', 'Thornton Wilder'),
(27, 'Gratitude is an antidote to negative emotions, a neutralizer of envy, hostility, worry, and irritation.', 'Robert Emmons'),
(28, 'The essence of all beautiful art, all great art, is gratitude.', 'Friedrich Nietzsche'),
(29, 'If you want to find happiness, find gratitude.', 'Steve Maraboli'),
(30, 'Gratitude is one of the most medicinal emotions we can feel. It elevates, energizes, inspires, and transforms.', 'Doc Childre'),
(31, 'Silent gratitude is not much use to anyone.', 'Gertrude Stein'),

-- February (Days 32-59)
(32, 'Let us rise up and be thankful, for if we didn''t learn a lot today, at least we learned a little.', 'Buddha'),
(33, 'Develop an attitude of gratitude, and give thanks for everything that happens to you.', 'Brian Tracy'),
(34, 'Gratitude is the memory of the heart.', 'Jean-Baptiste Massieu'),
(35, 'I would maintain that thanks are the highest form of thought; and that gratitude is happiness doubled by wonder.', 'G.K. Chesterton'),
(36, 'The more grateful I am, the more beauty I see.', 'Mary Davis'),
(37, 'Wear gratitude like a cloak, and it will feed every corner of your life.', 'Rumi'),
(38, 'What separates privilege from entitlement is gratitude.', 'Brené Brown'),
(39, 'Gratitude bestows reverence, allowing us to encounter everyday epiphanies.', 'John Milton'),
(40, 'When eating fruit, remember the one who planted the tree.', 'Vietnamese Proverb'),
(41, 'Joy is the simplest form of gratitude.', 'Karl Barth'),
(42, 'A grateful heart is a magnet for miracles.', 'Unknown'),
(43, 'It is not happiness that brings us gratitude. It is gratitude that brings us happiness.', 'Unknown'),
(44, 'The way to develop the best that is in a person is by appreciation and encouragement.', 'Charles Schwab'),
(45, 'At times, our own light goes out and is rekindled by a spark from another person. Each of us has cause to think with deep gratitude of those who have lighted the flame within us.', 'Albert Schweitzer'),
(46, 'If the only prayer you ever say in your entire life is thank you, it will be enough.', 'Meister Eckhart'),
(47, 'Thank you is the best prayer that anyone could say. Thank you expresses extreme gratitude, humility, understanding.', 'Alice Walker'),
(48, 'Gratitude is the healthiest of all human emotions. The more you express gratitude for what you have, the more likely you will have even more to express gratitude for.', 'Zig Ziglar'),
(49, 'Two kinds of gratitude: the sudden kind we feel for what we take, the larger kind we feel for what we give.', 'Edwin Arlington Robinson'),
(50, 'I don''t have to chase extraordinary moments to find happiness — it''s right in front of me if I''m paying attention and practicing gratitude.', 'Brené Brown'),
(51, 'When we focus on our gratitude, the tide of disappointment goes out and the tide of love rushes in.', 'Kristin Armstrong'),
(52, 'Gratitude opens the door to the power, the wisdom, the creativity of the universe.', 'Deepak Chopra'),
(53, 'Give thanks for a little and you will find a lot.', 'Hausa Proverb'),
(54, 'Enough is a feast.', 'Buddhist Proverb'),
(55, 'Trade your expectation for appreciation and the world changes instantly.', 'Tony Robbins'),
(56, 'Thankfulness is the beginning of gratitude. Gratitude is the completion of thankfulness.', 'Henri Frederic Amiel'),
(57, 'We often take for granted the very things that most deserve our gratitude.', 'Cynthia Ozick'),
(58, 'The unthankful heart discovers no mercies; but the thankful heart will find, in every hour, some heavenly blessings.', 'Henry Ward Beecher'),
(59, 'It''s a funny thing about life, once you begin to take note of the things you are grateful for, you begin to lose sight of the things that you lack.', 'Germany Kent'),

-- March (Days 60-90)
(60, 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.', 'Albert Einstein'),
(61, 'Start each day with a positive thought and a grateful heart.', 'Roy T. Bennett'),
(62, 'Some people grumble that roses have thorns; I am grateful that thorns have roses.', 'Alphonse Karr'),
(63, 'Gratitude helps you to grow and expand; gratitude brings joy and laughter into your life and into the lives of all those around you.', 'Eileen Caddy'),
(64, 'The soul that gives thanks can find comfort in everything; the soul that complains can find comfort in nothing.', 'Hannah Whitall Smith'),
(65, 'When we give cheerfully and accept gratefully, everyone is blessed.', 'Maya Angelou'),
(66, 'Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.', 'Epicurus'),
(67, 'True forgiveness is when you can say, Thank you for that experience.', 'Oprah Winfrey'),
(68, 'God gave you a gift of 86,400 seconds today. Have you used one to say thank you?', 'William Arthur Ward'),
(69, 'You cannot do a kindness too soon because you never know how soon it will be too late.', 'Ralph Waldo Emerson'),
(70, 'Reflect upon your present blessings, of which every man has plenty; not on your past misfortunes, of which all men have some.', 'Charles Dickens'),
(71, 'Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.', 'Voltaire'),
(72, 'I am happy because I''m grateful. I choose to be grateful. That gratitude allows me to be happy.', 'Will Arnett'),
(73, 'We should certainly count our blessings, but we should also make our blessings count.', 'Neal A. Maxwell'),
(74, 'The deepest craving of human nature is the need to be appreciated.', 'William James'),
(75, 'Cultivate the habit of being grateful for every good thing that comes to you, and to give thanks continuously.', 'Ralph Waldo Emerson'),
(76, 'Gratefulness is the key to a happy life that we hold in our hands, because if we are not grateful, then no matter how much we have we will not be happy.', 'David Steindl-Rast'),
(77, 'In all things give thanks.', '1 Thessalonians 5:18'),
(78, 'The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not.', 'Seneca'),
(79, 'To speak gratitude is courteous and pleasant, to enact gratitude is generous and noble, but to live gratitude is to touch Heaven.', 'Johannes A. Gaertner'),
(80, 'One can never pay in gratitude; one can only pay in kind somewhere else in life.', 'Anne Morrow Lindbergh'),
(81, 'Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude.', 'Denis Waitley'),
(82, 'I awoke this morning with devout thanksgiving for my friends, the old and the new.', 'Ralph Waldo Emerson'),
(83, 'This is a wonderful day. I''ve never seen this one before.', 'Maya Angelou'),
(84, 'The miracle is not to walk on water. The miracle is to walk on the green earth, dwelling deeply in the present moment and feeling truly alive.', 'Thich Nhat Hanh'),
(85, 'Let gratitude be the pillow upon which you kneel to say your nightly prayer.', 'Maya Angelou'),
(86, 'Every day, think as you wake up, today I am fortunate to be alive, I have a precious human life, I am not going to waste it.', 'Dalai Lama'),
(87, 'Appreciation can change a day, even change a life. Your willingness to put it into words is all that is necessary.', 'Margaret Cousins'),
(88, 'It is impossible to feel grateful and depressed in the same moment.', 'Naomi Williams'),
(89, 'Think of all the beauty still left around you and be happy.', 'Anne Frank'),
(90, 'Saying thank you is more than good manners. It is good spirituality.', 'Alfred Painter'),

-- April (Days 91-120)
(91, 'Look at everything always as though you were seeing it either for the first or last time.', 'Betty Smith'),
(92, 'Thankfulness creates gratitude which generates contentment that causes peace.', 'Todd Stocker'),
(93, 'There is a calmness to a life lived in gratitude, a quiet joy.', 'Ralph H. Blum'),
(94, 'Nothing is more honorable than a grateful heart.', 'Seneca'),
(95, 'The world has enough beautiful mountains and meadows. What the world needs more of is people to appreciate and enjoy it.', 'Michael Josephson'),
(96, 'Feeling grateful or appreciative of someone or something in your life actually attracts more of the things that you appreciate and value into your life.', 'Christiane Northrup'),
(97, 'When you practice gratefulness, there is a sense of respect toward others.', 'Dalai Lama'),
(98, 'Whatever we are waiting for — peace of mind, contentment, grace — it will surely come to us, but only when we are ready to receive it with an open and grateful heart.', 'Sarah Ban Breathnach'),
(99, 'There is no such thing as gratitude unexpressed. If it is unexpressed, it is plain, old-fashioned ingratitude.', 'Robert Brault'),
(100, 'Every blessing ignored becomes a curse.', 'Paulo Coelho'),
(101, 'Not what we say about our blessings, but how we use them, is the true measure of our thanksgiving.', 'W.T. Purkiser'),
(102, 'We must find time to stop and thank the people who make a difference in our lives.', 'John F. Kennedy'),
(103, 'What if you gave someone a gift, and they neglected to thank you for it — would you be likely to give them another? Life is the same way. In order to attract more of the blessings that life has to offer, you must truly appreciate what you already have.', 'Ralph Marston'),
(104, 'Gratitude is when memory is stored in the heart and not in the mind.', 'Lionel Hampton'),
(105, 'No duty is more urgent than giving thanks.', 'James Allen'),
(106, 'You pray in your distress and in your need; would that you might pray also in the fullness of your joy and in your days of abundance.', 'Khalil Gibran'),
(107, 'For me, every hour is grace. And I feel gratitude in my heart each time I can meet someone and look at his or her smile.', 'Elie Wiesel'),
(108, 'To educate yourself for the feeling of gratitude means to take nothing for granted.', 'Albert Schweitzer'),
(109, 'So much has been given to me; I have no time to ponder over that which has been denied.', 'Helen Keller'),
(110, 'I have learned that every heart will get what it prays for most.', 'Hafiz'),
(111, 'Appreciation is the highest form of prayer, for it acknowledges the presence of good wherever you shine the light of your thankful thoughts.', 'Alan Cohen'),
(112, 'The soul that gives thanks can find comfort in everything; the soul that complains can find comfort in nothing.', 'Hannah Whitall Smith'),
(113, 'We learned about gratitude and humility — that so many people had a hand in our success.', 'Michelle Obama'),
(114, 'The best way to show my gratitude to God is to accept everything, even my problems, with joy.', 'Mother Teresa'),
(115, 'There''s no happier person than a truly thankful, content person.', 'Joyce Meyer'),
(116, 'He who thanks but with the lips thanks but in part; the full, the true Thanksgiving comes from the heart.', 'J.A. Shedd'),
(117, 'Make it a habit to tell people thank you. To express your appreciation, sincerely and without the expectation of anything in return.', 'Ralph Marston'),
(118, 'I live in the space of thankfulness — and I have been rewarded a million times over for it.', 'Oprah Winfrey'),
(119, 'Gratitude paints little smiley faces on everything it touches.', 'Richelle E. Goodrich'),
(120, 'We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses.', 'Abraham Lincoln'),

-- May (Days 121-151)
(121, 'When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.', 'Marcus Aurelius'),
(122, 'The things you take for granted, someone else is praying for.', 'Unknown'),
(123, 'Let us be grateful to people who make us happy, they are the charming gardeners who make our souls blossom.', 'Marcel Proust'),
(124, 'Gratitude, like faith, is a muscle. The more you use it, the stronger it grows.', 'Alan Cohen'),
(125, 'Showing gratitude is one of the simplest yet most powerful things humans can do for each other.', 'Randy Pausch'),
(126, 'The greatest discovery of all time is that a person can change his future by merely changing his attitude.', 'Oprah Winfrey'),
(127, 'Walk as if you are kissing the Earth with your feet.', 'Thich Nhat Hanh'),
(128, 'What a wonderful life I''ve had! I only wish I''d realized it sooner.', 'Colette'),
(129, 'Those who are not grateful soon begin to complain of everything.', 'Thomas Merton'),
(130, 'We can always find something to be thankful for, and there may be reasons why we ought to be thankful for even those dispensations which appear dark and threatening.', 'Albert Barnes'),
(131, 'Gratitude doesn''t change the scenery. It merely washes clean the glass you look through so you can clearly see the colors.', 'Richelle E. Goodrich'),
(132, 'Hem your blessings with thankfulness so they don''t unravel.', 'Unknown'),
(133, 'Thankfulness is the quickest path to joy.', 'Jefferson Bethke'),
(134, 'You can''t be envious and happy at the same time.', 'Frank Tyger'),
(135, 'The only people with whom you should try to get even are those who have helped you.', 'John E. Southard'),
(136, 'A moment of gratitude makes a difference in your attitude.', 'Bruce Wilkinson'),
(137, 'An early-morning walk is a blessing for the whole day.', 'Henry David Thoreau'),
(138, 'Gratitude will shift you to a higher frequency, and you will attract much better things.', 'Rhonda Byrne'),
(139, 'You simply will not be the same person two months from now after consciously giving thanks each day for the abundance that exists in your life.', 'Sarah Ban Breathnach'),
(140, 'Every day is a gift; that''s why we call it the present.', 'Unknown'),
(141, 'We need to regularly stop and take stock; to sit down and determine within ourselves which things are worth valuing and which things are not.', 'Epictetus'),
(142, 'Dwell on the beauty of life. Watch the stars, and see yourself running with them.', 'Marcus Aurelius'),
(143, 'Take full account of what excellencies you possess, and in gratitude remember how you would hanker after them if you had them not.', 'Marcus Aurelius'),
(144, 'I am grateful for what I am and have. My thanksgiving is perpetual.', 'Henry David Thoreau'),
(145, 'Happiness is itself a kind of gratitude.', 'Joseph Wood Krutch'),
(146, 'Things turn out best for people who make the best of the way things turn out.', 'John Wooden'),
(147, 'Gratitude is riches. Complaint is poverty.', 'Doris Day'),
(148, 'You have no cause for anything but gratitude and joy.', 'Buddha'),
(149, 'I try to stay in a space of gratitude. I think about what people before me did so that I could have the life that I have.', 'Viola Davis'),
(150, 'The most important thing is to enjoy your life — to be happy — it''s all that matters.', 'Audrey Hepburn'),
(151, 'Today, let us swim wildly, joyfully, in gratitude.', 'Rumi'),

-- June (Days 152-181)
(152, 'Surrender to what is. Let go of what was. Have faith in what will be.', 'Sonia Ricotti'),
(153, 'Acknowledging the good that is already in your life is the foundation for all abundance.', 'Eckhart Tolle'),
(154, 'Feeling gratitude and not expressing it is like wrapping a present and not giving it.', 'William Arthur Ward'),
(155, 'A thankful heart is not only the greatest virtue, but the parent of all other virtues.', 'Cicero'),
(156, 'In the end, though, maybe we must all give up trying to pay back the people in this world who sustain our lives. In the end, maybe it''s wiser to surrender before the miraculous scope of human generosity and to just keep saying thank you, forever and sincerely.', 'Elizabeth Gilbert'),
(157, 'What you truly acknowledge truly is yours. Enjoy your blessings. Let them warm you.', 'Mary Anne Radmacher'),
(158, 'Gratitude can transform common days into thanksgivings, turn routine jobs into joy, and change ordinary opportunities into blessings.', 'William Arthur Ward'),
(159, 'Learn to be thankful for what you already have, while you pursue all that you want.', 'Jim Rohn'),
(160, 'Let your joy be in your journey — not in some distant goal.', 'Tim Cook'),
(161, 'A single sunbeam is enough to drive away many shadows.', 'Francis of Assisi'),
(162, 'If we magnified our blessings the way we magnify our disappointments, we would all be much happier.', 'John Wooden'),
(163, 'The only way to do great work is to love what you do.', 'Steve Jobs'),
(164, 'Count your rainbows, not your thunderstorms.', 'Alyssa Knight'),
(165, 'No act of kindness, no matter how small, is ever wasted.', 'Aesop'),
(166, 'Gratitude for the present moment and the fullness of life now is true prosperity.', 'Eckhart Tolle'),
(167, 'Those who bring sunshine to the lives of others cannot keep it from themselves.', 'J.M. Barrie'),
(168, 'In moments of gratitude, I find the greatest peace.', 'Unknown'),
(169, 'What you focus on expands. When you focus on the goodness in your life, you create more of it.', 'Oprah Winfrey'),
(170, 'The more you praise and celebrate your life, the more there is in life to celebrate.', 'Oprah Winfrey'),
(171, 'Sometimes the most important thing in a whole day is the rest we take between two deep breaths.', 'Etty Hillesum'),
(172, 'Be present in all things and thankful for all things.', 'Maya Angelou'),
(173, 'Life is not measured by the number of breaths we take, but by the moments that take our breath away.', 'Maya Angelou'),
(174, 'Every experience, no matter how bad it seems, holds within it a blessing of some kind. The goal is to find it.', 'Buddha'),
(175, 'Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.', 'Oprah Winfrey'),
(176, 'At the end of the day, let there be no excuses, no explanations, no regrets.', 'Steve Maraboli'),
(177, 'You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis'),
(178, 'Let today be the day you give up who you''ve been for who you can become.', 'Hal Elrod'),
(179, 'The secret of being happy is accepting where you are in life and making the most out of every day.', 'Unknown'),
(180, 'Be grateful for the home you have, knowing that at this moment, all you have is all you need.', 'Sarah Ban Breathnach'),
(181, 'When we lose one blessing, another is often most unexpectedly given in its place.', 'C.S. Lewis'),

-- July (Days 182-212)
(182, 'The greatest wealth is to live content with little.', 'Plato'),
(183, 'Find the good. It''s all around you. Find it, showcase it, and you''ll start believing in it.', 'Jesse Owens'),
(184, 'Happiness is not something readymade. It comes from your own actions.', 'Dalai Lama'),
(185, 'Today I choose to live with gratitude for the love that fills my heart, the peace that rests within my spirit, and the voice of hope that says all things are possible.', 'Unknown'),
(186, 'I have found that if you love life, life will love you back.', 'Arthur Rubinstein'),
(187, 'When you realize there is nothing lacking, the whole world belongs to you.', 'Lao Tzu'),
(188, 'Look at everything as though you are seeing it for the first time or the last time. Then your time on earth will be filled with glory.', 'Betty Smith'),
(189, 'It''s not what we have in life, but who we have in our life that matters.', 'J.M. Laurence'),
(190, 'If you look at what you have in life, you''ll always have more.', 'Oprah Winfrey'),
(191, 'Nothing can dim the light that shines from within.', 'Maya Angelou'),
(192, 'Act as if what you do makes a difference. It does.', 'William James'),
(193, 'The true secret of happiness lies in taking a genuine interest in all the details of daily life.', 'William Morris'),
(194, 'He who is not contented with what he has would not be contented with what he would like to have.', 'Socrates'),
(195, 'The greatest thing in the world is to know how to belong to oneself.', 'Michel de Montaigne'),
(196, 'Each day provides its own gifts.', 'Marcus Aurelius'),
(197, 'In the middle of every difficulty lies opportunity.', 'Albert Einstein'),
(198, 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson'),
(199, 'A grateful mind is a great mind which eventually attracts to itself great things.', 'Plato'),
(200, 'It is during our darkest moments that we must focus to see the light.', 'Aristotle'),
(201, 'The purpose of our lives is to be happy.', 'Dalai Lama'),
(202, 'When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.', 'Helen Keller'),
(203, 'There is more to life than increasing its speed.', 'Mahatma Gandhi'),
(204, 'Live life to the fullest, and focus on the positive.', 'Matt Cameron'),
(205, 'In three words I can sum up everything I''ve learned about life: it goes on.', 'Robert Frost'),
(206, 'The way I see it, if you want the rainbow, you gotta put up with the rain.', 'Dolly Parton'),
(207, 'Life is like a camera. Focus on the good times, develop from the negatives, and if things don''t work out, take another shot.', 'Ziad K. Abdelnour'),
(208, 'Blessed are they who see beautiful things in humble places where other people see nothing.', 'Camille Pissarro'),
(209, 'Write it on your heart that every day is the best day in the year.', 'Ralph Waldo Emerson'),
(210, 'Keep your face always toward the sunshine and shadows will fall behind you.', 'Walt Whitman'),
(211, 'In a gentle way, you can shake the world.', 'Mahatma Gandhi'),
(212, 'Wherever you go, go with all your heart.', 'Confucius'),

-- August (Days 213-243)
(213, 'Do what you can, with what you have, where you are.', 'Theodore Roosevelt'),
(214, 'Count your age by friends, not years. Count your life by smiles, not tears.', 'John Lennon'),
(215, 'For it is in giving that we receive.', 'Francis of Assisi'),
(216, 'We do not remember days, we remember moments.', 'Cesare Pavese'),
(217, 'Let us always meet each other with a smile, for the smile is the beginning of love.', 'Mother Teresa'),
(218, 'The more you are thankful, the more you attract things to be thankful for.', 'Unknown'),
(219, 'Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.', 'Lao Tzu'),
(220, 'Always have an attitude of gratitude.', 'Sterling K. Brown'),
(221, 'The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela'),
(222, 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', 'Anne Frank'),
(223, 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', 'Buddha'),
(224, 'With the new day comes new strength and new thoughts.', 'Eleanor Roosevelt'),
(225, 'Gratitude unlocks the fullness of life.', 'Melody Beattie'),
(226, 'An attitude of gratitude brings great things.', 'Yogi Bhajan'),
(227, 'It is only with the heart that one can see rightly; what is essential is invisible to the eye.', 'Antoine de Saint-Exupéry'),
(228, 'If I cannot do great things, I can do small things in a great way.', 'Martin Luther King Jr.'),
(229, 'We should all be thankful for those people who rekindle the inner spirit.', 'Albert Schweitzer'),
(230, 'The power of finding beauty in the humblest things makes home happy and life lovely.', 'Louisa May Alcott'),
(231, 'You have to participate relentlessly in the manifestation of your own blessings.', 'Elizabeth Gilbert'),
(232, 'Nobody can be uncheered with a balloon.', 'A.A. Milne'),
(233, 'The present moment is filled with joy and happiness. If you are attentive, you will see it.', 'Thich Nhat Hanh'),
(234, 'Let no one ever come to you without leaving better and happier.', 'Mother Teresa'),
(235, 'Don''t wait for someone to bring you flowers. Plant your own garden and decorate your own soul.', 'Luther Burbank'),
(236, 'One of the keys to happiness is a bad memory.', 'Rita Mae Brown'),
(237, 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'Albert Schweitzer'),
(238, 'For every minute you are angry you lose sixty seconds of happiness.', 'Ralph Waldo Emerson'),
(239, 'The best things in life are not things.', 'Art Buchwald'),
(240, 'What I know for sure is that what you give comes back to you.', 'Oprah Winfrey'),
(241, 'When you realize how precious and fragile life can be, it changes your whole perspective.', 'Ryan O''Donnell'),
(242, 'Tomorrow is a new day. You shall begin it well and serenely.', 'Ralph Waldo Emerson'),
(243, 'Live in the sunshine, swim the sea, drink the wild air.', 'Ralph Waldo Emerson'),

-- September (Days 244-273)
(244, 'To live is the rarest thing in the world. Most people exist, that is all.', 'Oscar Wilde'),
(245, 'Spread love everywhere you go. Let no one ever come to you without leaving happier.', 'Mother Teresa'),
(246, 'We are what we believe ourselves to be.', 'Paulo Coelho'),
(247, 'Patience is not the ability to wait, but the ability to keep a good attitude while waiting.', 'Joyce Meyer'),
(248, 'Strive not to be a success, but rather to be of value.', 'Albert Einstein'),
(249, 'The sun does not shine for a few trees and flowers, but for the wide world''s joy.', 'Henry Ward Beecher'),
(250, 'What great thing would you attempt if you knew you could not fail?', 'Robert H. Schuller'),
(251, 'Simplicity is the ultimate sophistication.', 'Leonardo da Vinci'),
(252, 'The best time to plant a tree was twenty years ago. The second best time is now.', 'Chinese Proverb'),
(253, 'Be yourself; everyone else is already taken.', 'Oscar Wilde'),
(254, 'In the sweetness of friendship let there be laughter, and sharing of pleasures.', 'Khalil Gibran'),
(255, 'Earth laughs in flowers.', 'Ralph Waldo Emerson'),
(256, 'It always seems impossible until it''s done.', 'Nelson Mandela'),
(257, 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius'),
(258, 'There is no path to happiness; happiness is the path.', 'Buddha'),
(259, 'Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.', 'Martin Luther'),
(260, 'Never let the odds keep you from doing what you know in your heart you were meant to do.', 'H. Jackson Brown Jr.'),
(261, 'We rise by lifting others.', 'Robert Ingersoll'),
(262, 'Turn your wounds into wisdom.', 'Oprah Winfrey'),
(263, 'A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.', 'George Bernard Shaw'),
(264, 'Whatever you do, do it with all your heart.', 'Confucius'),
(265, 'Choose to be optimistic; it feels better.', 'Dalai Lama'),
(266, 'The only thing we never get enough of is love; and the only thing we never give enough of is love.', 'Henry Miller'),
(267, 'Wherever there is a human being, there is an opportunity for a kindness.', 'Lucius Annaeus Seneca'),
(268, 'Be the change you wish to see in the world.', 'Mahatma Gandhi'),
(269, 'The most wasted of all days is one without laughter.', 'E.E. Cummings'),
(270, 'Life is either a daring adventure or nothing at all.', 'Helen Keller'),
(271, 'Adopt the pace of nature; her secret is patience.', 'Ralph Waldo Emerson'),
(272, 'The best portion of a good man''s life is his little, nameless, unremembered acts of kindness and of love.', 'William Wordsworth'),
(273, 'Every moment is a fresh beginning.', 'T.S. Eliot'),

-- October (Days 274-304)
(274, 'Until you learn to be grateful for the things you have, you will not receive the things you want.', 'John Kralik'),
(275, 'By being thankful for what I had, I realized that I had everything I needed.', 'John Kralik'),
(276, 'You don''t need more to be thankful. You need to be thankful for what you already have.', 'Unknown'),
(277, 'I may not be where I want to be but I''m thankful for not being where I used to be.', 'Habeeb Akande'),
(278, 'Let the beauty of what you love be what you do.', 'Rumi'),
(279, 'Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.', 'Bill Keane'),
(280, 'The greatest thing you''ll ever learn is just to love and be loved in return.', 'Eden Ahbez'),
(281, 'Kindness is the language which the deaf can hear and the blind can see.', 'Mark Twain'),
(282, 'The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt'),
(283, 'We know what we are, but know not what we may be.', 'William Shakespeare'),
(284, 'Don''t judge each day by the harvest you reap but by the seeds that you plant.', 'Robert Louis Stevenson'),
(285, 'The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt'),
(286, 'I can no other answer make but thanks, and thanks, and ever thanks.', 'William Shakespeare'),
(287, 'In everyone''s life, at some time, our inner fire goes out. It is then burst into flame by an encounter with another human being.', 'Albert Schweitzer'),
(288, 'Love the life you live. Live the life you love.', 'Bob Marley'),
(289, 'Believe you can and you''re halfway there.', 'Theodore Roosevelt'),
(290, 'What we think, we become.', 'Buddha'),
(291, 'Goodness is the only investment that never fails.', 'Henry David Thoreau'),
(292, 'The invariable mark of wisdom is to see the miraculous in the common.', 'Ralph Waldo Emerson'),
(293, 'You must be the change you wish to see in the world.', 'Mahatma Gandhi'),
(294, 'I have not failed. I''ve just found 10,000 ways that won''t work.', 'Thomas A. Edison'),
(295, 'The only journey is the one within.', 'Rainer Maria Rilke'),
(296, 'Be faithful in small things because it is in them that your strength lies.', 'Mother Teresa'),
(297, 'Peace begins with a smile.', 'Mother Teresa'),
(298, 'Difficulties are things that show a person what they are.', 'Epictetus'),
(299, 'Every day may not be good, but there''s something good in every day.', 'Alice Morse Earle'),
(300, 'It does not matter how slowly you go as long as you do not stop.', 'Confucius'),
(301, 'How lucky I am to have something that makes saying goodbye so hard.', 'A.A. Milne'),
(302, 'Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.', 'Rumi'),
(303, 'A beautiful day begins with a beautiful mindset.', 'John Geiger'),
(304, 'That which does not kill us makes us stronger.', 'Friedrich Nietzsche'),

-- November (Days 305-334)
(305, 'It is not how much we have, but how much we enjoy, that makes happiness.', 'Charles Spurgeon'),
(306, 'If you change the way you look at things, the things you look at change.', 'Wayne Dyer'),
(307, 'The world is full of magical things patiently waiting for our wits to grow sharper.', 'Bertrand Russell'),
(308, 'Every day brings a chance for you to draw in a breath, kick off your shoes, and dance.', 'Oprah Winfrey'),
(309, 'You can, you should, and if you are brave enough to start, you will.', 'Stephen King'),
(310, 'It is health that is real wealth and not pieces of gold and silver.', 'Mahatma Gandhi'),
(311, 'The little things? The little moments? They aren''t little.', 'Jon Kabat-Zinn'),
(312, 'Grace isn''t a little prayer you chant before receiving a meal. It''s a way to live.', 'Jacqueline Winspear'),
(313, 'Look deep into nature, and then you will understand everything better.', 'Albert Einstein'),
(314, 'Not all of us can do great things. But we can do small things with great love.', 'Mother Teresa'),
(315, 'The question isn''t who is going to let me; it''s who is going to stop me.', 'Ayn Rand'),
(316, 'I am beginning to learn that it is the sweet, simple things of life which are the real ones after all.', 'Laura Ingalls Wilder'),
(317, 'Every saint has a past, and every sinner has a future.', 'Oscar Wilde'),
(318, 'Where there is love there is life.', 'Mahatma Gandhi'),
(319, 'The soul is healed by being with children.', 'Fyodor Dostoevsky'),
(320, 'We make a living by what we get, but we make a life by what we give.', 'Winston Churchill'),
(321, 'Correction does much, but encouragement does more.', 'Johann Wolfgang von Goethe'),
(322, 'A warm smile is the universal language of kindness.', 'William Arthur Ward'),
(323, 'In the end, it''s not the years in your life that count. It''s the life in your years.', 'Abraham Lincoln'),
(324, 'Those who are happiest are those who do the most for others.', 'Booker T. Washington'),
(325, 'If I had my life to live over, I would start barefoot earlier in the spring and stay that way later in the fall.', 'Nadine Stair'),
(326, 'The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius'),
(327, 'You are imperfect, permanently and inevitably flawed. And you are beautiful.', 'Amy Bloom'),
(328, 'Sometimes the smallest things take up the most room in your heart.', 'A.A. Milne'),
(329, 'Where attention goes, energy flows. Where intention goes, energy flows.', 'James Redfield'),
(330, 'Happiness always looks small while you hold it in your hands, but let it go, and you learn at once how big and precious it is.', 'Maxim Gorky'),
(331, 'When one has a grateful heart, life is so beautiful.', 'Roy T. Bennett'),
(332, 'Life isn''t about finding yourself. Life is about creating yourself.', 'George Bernard Shaw'),
(333, 'The grand essentials of happiness are: something to do, something to love, and something to hope for.', 'Allan K. Chalmers'),
(334, 'Think of what a better world it would be if we all, the whole world, had cookies and milk about three o''clock every afternoon and then lay down on our blankets for a nap.', 'Barbara Jordan'),

-- December (Days 335-366)
(335, 'Acknowledging the good that is already in your life is the foundation for all abundance.', 'Eckhart Tolle'),
(336, 'The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson'),
(337, 'If you look to others for fulfillment, you will never be fulfilled. If your happiness depends on money, you will never be happy with yourself. Be content with what you have; rejoice in the way things are.', 'Lao Tzu'),
(338, 'We can never obtain peace in the outer world until we make peace with ourselves.', 'Dalai Lama'),
(339, 'Be kind whenever possible. It is always possible.', 'Dalai Lama'),
(340, 'Those who wish to sing always find a song.', 'Swedish Proverb'),
(341, 'Life is 10% what happens to you and 90% how you react to it.', 'Charles R. Swindoll'),
(342, 'You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.', 'Albert Camus'),
(343, 'A friend is someone who gives you total freedom to be yourself.', 'Jim Morrison'),
(344, 'The most beautiful things in the world cannot be seen or touched. They are felt with the heart.', 'Antoine de Saint-Exupéry'),
(345, 'The only true wisdom is in knowing you know nothing.', 'Socrates'),
(346, 'Out of difficulties grow miracles.', 'Jean de La Bruyère'),
(347, 'Rest is not idleness, and to lie sometimes on the grass under trees on a summer''s day, listening to the murmur of the water, is by no means a waste of time.', 'John Lubbock'),
(348, 'We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves.', 'Buddha'),
(349, 'What sunshine is to flowers, smiles are to humanity.', 'Joseph Addison'),
(350, 'No one has ever become poor by giving.', 'Anne Frank'),
(351, 'The measure of who we are is what we do with what we have.', 'Vince Lombardi'),
(352, 'Life is too important to be taken seriously.', 'Oscar Wilde'),
(353, 'Learn from yesterday, live for today, hope for tomorrow.', 'Albert Einstein'),
(354, 'The good life is one inspired by love and guided by knowledge.', 'Bertrand Russell'),
(355, 'If you realize that you have enough, you are truly rich.', 'Lao Tzu'),
(356, 'When the world says give up, hope whispers try it one more time.', 'Unknown'),
(357, 'It is in your moments of decision that your destiny is shaped.', 'Tony Robbins'),
(358, 'What you do makes a difference, and you have to decide what kind of difference you want to make.', 'Jane Goodall'),
(359, 'Joy does not simply happen to us. We have to choose joy and keep choosing it every day.', 'Henri Nouwen'),
(360, 'When you are content to be simply yourself and don''t compare or compete, everyone will respect you.', 'Lao Tzu'),
(361, 'Forever is composed of nows.', 'Emily Dickinson'),
(362, 'The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.', 'Helen Keller'),
(363, 'Gratitude is a quality similar to electricity: it must be produced and discharged and used up in order to exist at all.', 'William Faulkner'),
(364, 'Everything has beauty, but not everyone sees it.', 'Confucius'),
(365, 'This is the day that the Lord has made; let us rejoice and be glad in it.', 'Psalm 118:24'),
(366, 'Let us be grateful to the mirror for revealing to us our appearance only.', 'Samuel Butler');
